spring:
  datasource:
    url: jdbc:mysql://123.56.116.34:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  session:
    timeout: 86400 # session 失效时间

server:
  port: 8080
  servlet:
    context-path: /api